apiVersion: v1
kind: Pod
metadata:
  name: playing-with-kubernetes
  labels:
    name: playing-with-kubernetes
spec:
  containers:
  - name: playing-with-kubernetes
    image: playing-with-kubernetes
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "10M"
        cpu: "20m"
      limits:
        memory: "20M"
        cpu: "20m"
    

    
    