replicaCount: 3

image:
  repository: playing-with-kubernetes
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "10M"
    cpu: "20m"
  limits:
    memory: "20M"
    cpu: "20m"